//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerUserMaster
    {
        public CustomerUserMaster()
        {
            this.FeedBackHistories = new HashSet<FeedBackHistory>();
            this.TestimonialHistories = new HashSet<TestimonialHistory>();
            this.UserServicesUsedHistories = new HashSet<UserServicesUsedHistory>();
            this.UserServiceInfoes = new HashSet<UserServiceInfo>();
        }
    
        public int CustomerUserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Age { get; set; }
    
        public virtual ICollection<FeedBackHistory> FeedBackHistories { get; set; }
        public virtual ICollection<TestimonialHistory> TestimonialHistories { get; set; }
        public virtual ICollection<UserServicesUsedHistory> UserServicesUsedHistories { get; set; }
        public virtual ICollection<UserServiceInfo> UserServiceInfoes { get; set; }
    }
}
