//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProUserCategoryMapping
    {
        public int ProUserCategoryMappingID { get; set; }
        public int CategoryID { get; set; }
        public int ProUserID { get; set; }
        public int SubCategoryID { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual ProUserMaster ProUserMaster { get; set; }
        public virtual SubCategoryMaster SubCategoryMaster { get; set; }
    }
}
