//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMaster
    {
        public QuestionMaster()
        {
            this.UserServiceInfoes = new HashSet<UserServiceInfo>();
        }
    
        public int QuestionMasterID { get; set; }
        public string Question { get; set; }
        public string Options { get; set; }
        public string ValidationType { get; set; }
        public bool IsValidation { get; set; }
        public int SubCategoryID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual SubCategoryMaster SubCategoryMaster { get; set; }
        public virtual ICollection<UserServiceInfo> UserServiceInfoes { get; set; }
    }
}
