//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryMaster
    {
        public SubCategoryMaster()
        {
            this.ProUserCategoryMappings = new HashSet<ProUserCategoryMapping>();
            this.QuestionMasters = new HashSet<QuestionMaster>();
            this.UserServiceInfoes = new HashSet<UserServiceInfo>();
            this.UserServicesUsedHistories = new HashSet<UserServicesUsedHistory>();
        }
    
        public int SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public int CategoryID { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual ICollection<ProUserCategoryMapping> ProUserCategoryMappings { get; set; }
        public virtual ICollection<QuestionMaster> QuestionMasters { get; set; }
        public virtual ICollection<UserServiceInfo> UserServiceInfoes { get; set; }
        public virtual ICollection<UserServicesUsedHistory> UserServicesUsedHistories { get; set; }
    }
}
