//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServiceInfo
    {
        public int UserServiceInfoID { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Answer { get; set; }
        public string Address { get; set; }
        public int CustomerUserID { get; set; }
        public System.DateTime ServiceDateTime { get; set; }
        public int UserServicesUsedHistoryID { get; set; }
        public int QuestionMasterID { get; set; }
        public int SubCategoryID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual CustomerUserMaster CustomerUserMaster { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
        public virtual SubCategoryMaster SubCategoryMaster { get; set; }
        public virtual UserServicesUsedHistory UserServicesUsedHistory { get; set; }
    }
}
