//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMaster
    {
        public CategoryMaster()
        {
            this.ProUserCategoryMappings = new HashSet<ProUserCategoryMapping>();
            this.QuestionMasters = new HashSet<QuestionMaster>();
            this.SubCategoryMasters = new HashSet<SubCategoryMaster>();
            this.UserServiceInfoes = new HashSet<UserServiceInfo>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual ICollection<ProUserCategoryMapping> ProUserCategoryMappings { get; set; }
        public virtual ICollection<QuestionMaster> QuestionMasters { get; set; }
        public virtual ICollection<SubCategoryMaster> SubCategoryMasters { get; set; }
        public virtual ICollection<UserServiceInfo> UserServiceInfoes { get; set; }
    }
}
