//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBackHistory
    {
        public int FeedbackHistoryID { get; set; }
        public int Timeliness { get; set; }
        public int Quality { get; set; }
        public int Behavior { get; set; }
        public int UserServicesUsedHistoryID { get; set; }
        public int CustomerUserID { get; set; }
    
        public virtual CustomerUserMaster CustomerUserMaster { get; set; }
        public virtual UserServicesUsedHistory UserServicesUsedHistory { get; set; }
    }
}
