//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProUserWorkLocationMapping
    {
        public int ProUserWorkLocationMappingID { get; set; }
        public int ProUserID { get; set; }
        public int WorkLocationMasterID { get; set; }
    
        public virtual ProUserMaster ProUserMaster { get; set; }
        public virtual WorkLocationsMaster WorkLocationsMaster { get; set; }
    }
}
