//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProUserMaster
    {
        public ProUserMaster()
        {
            this.ProUserCategoryMappings = new HashSet<ProUserCategoryMapping>();
            this.ProUserWorkTimingsMappings = new HashSet<ProUserWorkTimingsMapping>();
            this.ProUserWorkLocationMappings = new HashSet<ProUserWorkLocationMapping>();
        }
    
        public int ProUserIdD { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Experience { get; set; }
        public string OfficialTrainingCertification { get; set; }
        public string EducationLevel { get; set; }
        public string LanguagesSpoken { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ICollection<ProUserCategoryMapping> ProUserCategoryMappings { get; set; }
        public virtual ICollection<ProUserWorkTimingsMapping> ProUserWorkTimingsMappings { get; set; }
        public virtual ICollection<ProUserWorkLocationMapping> ProUserWorkLocationMappings { get; set; }
    }
}
