//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTimingsMaster
    {
        public WorkTimingsMaster()
        {
            this.ProUserWorkTimingsMappings = new HashSet<ProUserWorkTimingsMapping>();
        }
    
        public int WorkTimingMasterID { get; set; }
        public string WorkTiming { get; set; }
    
        public virtual ICollection<ProUserWorkTimingsMapping> ProUserWorkTimingsMappings { get; set; }
    }
}
